### ISSUE TITLE
Links between species are incorrect

### ISSUE THREAD

**Issue by therohk** [bricaud/tree-of-life-dataset#1]
I am posting this note here since this repository is top result on google for a tree of life dataset.

The links between species available under "links" within the json file `data/treeoflife.json` are totally wrong.

A dataset extracted from the same source xml file that contains correct mappings is available for download on kaggle: https://www.kaggle.com/konivat/tree-of-life

This issue can be seen by evaluating the species ancestry for `Homo sapiens`. 

```
16421 Homo sapiens
16404 None
16401 Procolobus
16336 <missing node>
```
It also lists humans as the ancestor for two species of rodents.

Compared to the dataset posted on kaggle : 

```
16421 Homo sapiens
16418 Homo
16416 none
16414 none
16412 none
16411 none
16299 Hominidae
16298 none
16293 Catarrhini
16291 none
16290 none
15963 Primates
15962 none
15961 none
15955 none
15997 Eutheria
15995 none
15993 none
15990 none
15040 Mammalia
15030 Cynodontia
15028 none
15026 Theriodontia
14973 Therapsida
14971 Sphenacodontoidea
14969 none
14967 none
14965 none
14963 Sphenacodontia
14961 none
14959 none
14957 Eupelycosauria
14845 Synapsida
14990 Amniota
14989 none
14988 Reptiliomorpha
14987 Tetrapoda
14986 none
14985 none
14984 none
14983 none
14982 none
14981 none
14980 none
14979 none
14978 none
14977 none
14976 none
14975 none
14952 Terrestrial Vertebrates
14950 none
14948 none
14944 none
14922 Sarcopterygii
14921 Osteichthyes
14920 Teleostomi
14919 Node 1
14843 Gnathostomata
14840 Node 3
14838 Node 2
14836 none
14833 Node 1
14829 Vertebrata
14826 Craniata
14822 none
14820 none
2499 Chordata
2466 Deuterostomia
2459 Bilateria
2458 none
2374 Animals
2373 none
2372 Opisthokonts
3 Eukaryotes
1 Life on Earth
```

**Comment by bricaud** [comment]
Thank you for your feedback @therohk ! I have corrected the json file. In the meantime, I have updated the jupyter notebook that explore the data and make the json file. I do not know why it was wrong.

**Comment by bricaud** [comment]
I also added a link to your Kaggle repo in the readme file.
Thanks again!
